### ISSUE TITLE
Interested in cooperation

### ISSUE THREAD

**Issue by he-yang** [toogad/PooPyLab_Project#1]
Dear Dr Zhang,

I posted an issue last month, but I couldn't find it now, so I am opening a new issue.

Currently I am working on an open source project OpenDesignWWTP which targets for wastewater treatment plant design. Your project PooPyLab may be of great importance to OpenDesignWWTP as ASM could be used for biological treatment units optimization/design.

Could you please have a look at my repository (i've just started this project ), and send me your thoughts and ideas about cooperation.

Regards,
He Yang

**Comment by toogad** [comment]
He,

First of all, please simply call me Kai.

Sorry for the inconvenience in the change of github repository. I was
playing with github, trying to make the folder more "professional". So the
old folders were removed. PooPyLab_Project is now the new repo name. And I
am pushing updates into the develop branch, instead of the master which is
meant for stable release.

Surely I am interested in colaboration. I will look into your project and
see if we can work together on it. I am no expert in programming or
software project management though. If you have any suggestions/thoughts on
PooPyLab, please let me know as well.

Thank you.

Regards,

Kai

On Thu, Nov 13, 2014 at 5:34 AM, He Yang notifications@github.com wrote:

> Dear Dr Zhang,
> 
> I posted an issue last month, but I couldn't find it now, so I am opening
> a new issue.
> 
> Currently I am working on an open source project OpenDesignWWTP which
> targets for wastewater treatment plant design. Your project PooPyLab may be
> of great importance to OpenDesignWWTP as ASM could be used for biological
> treatment units optimization/design.
> 
> Could you please have a look at my repository (i've just started this
> project ), and send me your thoughts and ideas about cooperation.
> 
> Regards,
> He Yang
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/toogad/PooPyLab_Project/issues/1.

## 

Kai Zhang

---

Coincidence is God's way of remaining anonymous.

**Comment by he-yang** [comment]
Hi Kai,

Our projects, obviously, will continue to run independently. What we could work together, at this moment, is to build up an interface/API between our projects. Interface, to my knowledge, is nothing different than calling a function, eg. interface(var1,var2,var3...). OpenDesignWWTP will call interface() and send you variables/parameters and PooPyLab will run the simulation and push results back to OpenDesignWWTP. The important thing is that we must make sure both of our program should be able to understand and interpret all the "stuff" transferred via this interface. I will try to read you py file and hopefully, I could understand it and send you more.

regards,
He

**Comment by toogad** [comment]
He,

I agree. I will keep deveoping PooPyLab and keep the interface to
OpenDesignWWTP in my mind. We can check into each other from time to time
to see the status on both sides.

Are you an engineer in US? What firm/school do you work for?

Kai

On Thu, Nov 13, 2014 at 6:23 PM, He Yang notifications@github.com wrote:

> Hi Kai,
> 
> Our projects, obviously, will continue to run independently. What we could
> work together, at this moment, is to build up an interface/API between our
> projects. Interface, to my knowledge, is nothing different than calling a
> function, eg. interface(var1,var2,var3...). OpenDesignWWTP will call
> interface() and send you variables/parameters and PooPyLab will run the
> simulation and push results back to OpenDesignWWTP. The important thing is
> that we must make sure both of our program should be able to understand and
> interpret all the "stuff" transferred via this interface. I will try to
> read you py file and hopefully, I could understand it and send you more.
> 
> regards,
> He
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/toogad/PooPyLab_Project/issues/1#issuecomment-62991536
> .

## 

Kai Zhang

---

Coincidence is God's way of remaining anonymous.

**Comment by he-yang** [comment]
Kai,

Last weekend, I read some brief introduction to Python, and found this language not that difficult, and then I tried to identify the solver you employed for DAEs problem, but failed. Maybe it was because my Python skills was not good enough.

Soon, I will make a list of parameters and variables that OpenDesignWWTP may send to PooPyLab, so that you may have this in mind during PooPyLab development. 

Regarding my work, I am working for a local environmental engineering design firm in Beijing as a process engineer in the water/wastewater engineering field. Could you maybe tell me about your work, are you a engineer in the States? OpenDesignWWTP is dedicated to sharing various 'design styles' with everybody, it would definitely be great if you could share some of your experience with us. 

Regards,
He

**Comment by toogad** [comment]
He,

For steady state, which is the first stage of the project, I am using the
fsolve() function in the scipy package. You can find it in scipy.optimize
subdivision. Scipy is not part of standard Python library.

I am working for CH2M Hill in Houston, TX. Just like you, I am a process
engineer in the water business group. The Houston office focuses on
industrial wastewater such as refineries and chemical companies.

Regards,

Kai

On Tue, Nov 18, 2014 at 6:37 PM, He Yang notifications@github.com wrote:

> Kai,
> 
> Last weekend, I read some brief introduction to Python, and found this
> language not that difficult, and then I tried to identify the solver you
> employed for DAEs problem, but failed. Maybe it was because my Python
> skills was not good enough.
> 
> Soon, I will make a list of parameters and variables that OpenDesignWWTP
> may send to PooPyLab, so that you may have this in mind during PooPyLab
> development.
> 
> Regarding my work, I am working for a local environmental engineering
> design firm in Beijing as a process engineer in the water/wastewater
> engineering field. Could you maybe tell me about your work, are you a
> engineer in the States? OpenDesignWWTP is dedicated to sharing various
> 'design styles' with everybody, it would definitely be great if you could
> share some of your experience with us.
> 
> Regards,
> He
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/toogad/PooPyLab_Project/issues/1#issuecomment-63573173
> .

## 

Kai Zhang

---

Coincidence is God's way of remaining anonymous.

**Comment by he-yang** [comment]
Hi Kai,

Great to know that you are also in the process engineer community :)

Most of the time, I work on municipal water/wastewater treatment plant projects. In China , there are handy design manuals /codes/regulations available to us, and I simply need to consult these documentations and follow the instructions, with some easy calculations, the design(sizing) can be done. How about the situation in the States, are there manuals/codes/regulations you can consult, or you have to do the design with mass balances and modelling ? If there are documentation for design, what are they?

Regards,
He

**Comment by toogad** [comment]
He,

We do have design guidelines here in US for both municipal and industrial
applications. Between the two, I would say the guidelines for municipal
applications are more comprehensive. There are regulations from the
federal, to state, to local levels. For industrial projects, the guidelines
may not come from the governmental agencies. Instead, more info is given by
the specific industries we are dealing with.

For biological treatment alone, municipal projects get fairly consistent
influent characteristics, from COD/BOD, to N/P etc. Big difference in
effluent requirements. Some states, such as Florida, has very low nutrient
limits. TN3 and TP0.1 are not uncommon. Some other state, such as Texas,
mainly require BOD and TSS removal, nutrient limits are way behind other
states. With many low effluent nutrient plants, simulation is almost always
required during the design.

Industrial biological treatment, on the contrary, may or may not have low
effluent nutrient limits. However, their influent characteristics are
wildly different from one to another, sometimes with unrealistically high
nitrogen. Overall, the percent N removal is still significant and require
simulation to verify. There are some industrial wastewaters that go to the
other extreme, ultra high COD, but no nutrient.

Regardless the wastewater types and effluent requirements, simulation is
quite a standard practice. It offers some optimization in the design and
let the engineer to quickly assess multiple configurations or scenarios.

Kai

On Thu, Nov 20, 2014 at 12:42 AM, He Yang notifications@github.com wrote:

> Hi Kai,
> 
> Great to know that you are also in the process engineer community :)
> 
> Most of the time, I work on municipal water/wastewater treatment plant
> projects. In China , there are handy design manuals /codes/regulations
> available to us, and I simply need to consult these documentations and
> follow the instructions, with some easy calculations, the design(sizing)
> can be done. How about the situation in the States, are there
> manuals/codes/regulations you can consult, or you have to do the design
> with mass balances and modelling ? If there are documentation for design,
> what are they?
> 
> Regards,
> He
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/toogad/PooPyLab_Project/issues/1#issuecomment-63767532
> .

## 

Kai Zhang

---

Coincidence is God's way of remaining anonymous.

**Comment by he-yang** [comment]
Kai,

Thank you very much for sharing your experience with us.

It seems like the situation in the States is quite similar to the one in Mainland China with respect to guidelines/regulations/codes, but I may assume the design process in China is much simpler than the one in US because simulations are hardly done here.

Lately, I found several books, for instance "Design of municipal wastewater treatment plant" co-published by Water Environment Federation and American Society of Civil Engineers. Have you ever used this book for your design? Does "Wastewater Engineering" by Metcalf & Eddy play an important role in your work?

and ...
I've made a tentative list of arguments that OpenDesignWWTP may pass to PooPyLab

Design_OpenDesignWWTP (info, influent)
info: Array, currently has 2 elements
       info[0] --Type of influent data. could be 0 or 1.       0->Simplified, 1->detailed
       info[1] --Type of reactor. could be 0 or ....      0->CSTR
influent: Dict, 
       COD,BOD,TN,TP,NH3-N  which corresponds to info[0]
       rb,nrb,O,NH.....(your NOMENCLATURE list) which corresponds to info[1]

This is still a tentative proposal.

Regards,
He

**Comment by toogad** [comment]
He,

Thanks for the info for connecting the two applications. I will keep those
in mind when writing the PooPyLab codes.

Both books that you mentioned are quite useful in our process design for
municipal projects. For industrial applications, they serve as general
guidelines for individual processes. Specific considerations are most
likely required as industrial WW were different from one to another. In
modeling/simulation, treatability tests to determine kinetic parameters are
quite common as well.

Regards,

Kai

On Sun, Nov 23, 2014 at 7:44 PM, He Yang notifications@github.com wrote:

> Kai,
> 
> Thank you very much for sharing your experience with us.
> 
> It seems like the situation in the States is quite similar to the one in
> Mainland China with respect to guidelines/regulations/codes, but I may
> assume the design process in China is much simpler than the one in US
> because simulations are hardly done here.
> 
> Lately, I found several books, for instance "Design of municipal
> wastewater treatment plant" co-published by Water Environment Federation
> and American Society of Civil Engineers. Have you ever used this book for
> your design? Does "Wastewater Engineering" by Metcalf & Eddy play an
> important role in your work?
> 
> and ...
> I've made a tentative list of arguments that OpenDesignWWTP may pass to
> PooPyLab
> 
> Design_OpenDesignWWTP (info, influent)
> info: Array, currently has 2 elements
> info[0] --Type of influent data. could be 0 or 1. 0->Simplified,
> 1->detailed
> info[1] --Type of reactor. could be 0 or .... 0->CSTR
> influent: Dict,
> COD,BOD,TN,TP,NH3-N which corresponds to info[0]
> rb,nrb,O,NH.....(your NOMENCLATURE list) which corresponds to info[1]
> 
> This is still a tentative proposal.
> 
> Regards,
> He
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/toogad/PooPyLab_Project/issues/1#issuecomment-64144839
> .

## 

Kai Zhang

---

Coincidence is God's way of remaining anonymous.
