### ISSUE TITLE
Control Strategies-Simulator

### ISSUE THREAD

**Issue by ghost** [toogad/PooPyLab_Project#12]
Hello,

I am terribly sorry that i am writing a question on Issues but i can not find a Discussion section.

I am considering to use your simulator for trying MPC control. Is this possible? Also i can customize the simulator to a real WWTP in terms of number of nitrification tanks, denitrification tanks, settlers, concentrations etc?

Thanks in advance

Giannis

**Comment by toogad** [comment]
Giannis,

Please note the limitations of the current version of PooPyLab:

1) It only does steady state simulation; I believe MPC will require a dynamic
simulator (will be built as part of future PooPyLab version);

2) Settler is "perfect" to the TSS capture rate the user specifies (i.e. it
doesn't have a "10-layer" model inside the unit);

3) It is on ASM1 so bio-P is not part of the calculations

You can follow the examples to set up multiple process zones for N/dN.

If you do tinker with it, I would be grateful to hear your feedbacks.

Thanks.

KZ

**Comment by ghost** [comment]
Hello Kai,

I would like to say again thank you for your immediate response and congratulations for your work.

Yes, we would need a dynamic simulator for MPC.

I will send an email if we finally decide to use it!

Best Regards!

Giannis
________________________________
Από: toogad ***@***.***>
Στάλθηκε: Τρίτη, 14 Μαρτίου 2023 3:28 μμ
Προς: toogad/PooPyLab_Project ***@***.***>
Κοιν.: MiloBestRegards ***@***.***>; Author ***@***.***>
Θέμα: Re: [toogad/PooPyLab_Project] Control Strategies-Simulator (Issue #12)


Giannis,

Please note the limitations of the current version of PooPyLab:

1) It only does steady state simulation; I believe MPC will require a dynamic
simulator (will be built as part of future PooPyLab version);

2) Settler is "perfect" to the TSS capture rate the user specifies (i.e. it
doesn't have a "10-layer" model inside the unit);

3) It is on ASM1 so bio-P is not part of the calculations

You can follow the examples to set up multiple process zones for N/dN.

If you do tinker with it, I would be grateful to hear your feedbacks.

Thanks.

KZ

**Comment by toogad** [comment]
Will consider such a feature.
